# Generated by Django 5.2.7 on 2025-10-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='photo',
        ),
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name='Длииное описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'verbose_name': 'Картинка места',
                'verbose_name_plural': 'Картинки места',
                'ordering': ['order'],
            },
        ),
    ]
