# Generated by Django 5.2.7 on 2025-10-24 17:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_address_remove_place_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Длинное описание'),
        ),
    ]
